data_and_analytics_dbt_bha_ladders:
  target: dev  
  outputs:
    dev:
      account: "{{ env_var('DBT_SNOWFLAKE_GCP_ACCOUNT') }}"
      database: DM_LADDERS_DEV
      password: "{{ env_var('DBT_SNOWFLAKE_PWD_BHA') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_GCP_ROLE') }}"
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER_BHA') }}"
      warehouse: COMPUTE_WH
    qa:
      account: "{{ env_var('DBT_SNOWFLAKE_GCP_ACCOUNT') }}"
      database: DM_LADDERS_QA
      password: "{{ env_var('DBT_SNOWFLAKE_PWD_BHA') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_GCP_ROLE') }}"
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER_BHA') }}"
      warehouse: COMPUTE_WH
    prod:
      account: "{{ env_var('DBT_SNOWFLAKE_GCP_ACCOUNT') }}"
      database: DM_LADDERS_PROD
      password: "{{ env_var('DBT_SNOWFLAKE_PWD_BHA') }}"
      role: "{{ env_var('DBT_SNOWFLAKE_GCP_ROLE') }}"
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER_BHA') }}"
      warehouse: COMPUTE_WH      
    test-location:
      account: "{{ env_var('DBT_SNOWFLAKE_GCP_ACCOUNT') }}"
      database: DM_LADDERS_BHA_LOCATION_REDESIGN_1
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
    test-perf:
      account: "{{ env_var('DBT_SNOWFLAKE_GCP_ACCOUNT') }}"
      database: DM_LADDERS_PERF
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH
    test-train:
      account: "{{ env_var('DBT_SNOWFLAKE_GCP_ACCOUNT') }}"
      database: DM_LADDERS_TRAIN
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH      
    test:
      account: "{{ env_var('DBT_SNOWFLAKE_GCP_ACCOUNT') }}"
      database: DM_LADDERS_TEST
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH     
    test-staging:
      account: "{{ env_var('DBT_SNOWFLAKE_GCP_ACCOUNT') }}"
      database: DM_LADDERS_TEST_STAGING
      password: "{{ env_var('DBT_SNOWFLAKE_PWD') }}"
      role: user_dbt_test
      schema: DM
      threads: 1
      type: snowflake
      user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
      warehouse: COMPUTE_WH             