models:
  - name: VW_CLINICS_CREATE_UPDATE
    columns:
    - name: PARENT_CASE_ID
      data_tests:
      - relationships:
              to: "{{ source('dm_table_data', 'CASE_PROVIDER') }}"
              field: CASE_ID
    - name: OWNER_ID
      data_tests:
      - relationships:
              to: "{{ source('dm_table_data', 'LOCATION') }}"
              field: ID
    - name: DISPLAY_NAME
      data_tests:
      - string_not_empty
    - name: CLINIC_TYPE
      data_tests:
      - string_not_empty
      - split_value_not_in_fixture:
              ref_fixture: 'FIXTURE_CLINIC_TYPE'
    - name: MENTAL_HEALTH_SETTINGS
      data_tests:
      - split_value_not_in_fixture:
              ref_fixture: 'FIXTURE_MENTAL_HEALTH_SETTINGS'
    - name: SERVICE_TYPES
      data_tests:
      - split_value_not_in_fixture:
              ref_fixture: 'FIXTURE_SERVICE_TYPES'
    - name: INSURANCE
      data_tests:
      - split_value_not_in_fixture:
              ref_fixture: 'FIXTURE_INSURANCE'
    - name: RESIDENTIAL_SERVICES
      data_tests:
      - split_value_not_in_fixture:
              ref_fixture: 'FIXTURE_RESIDENTIAL_SERVICES'
    - name: POPULATION_SERVED
      data_tests:
      - split_value_not_in_fixture:
              ref_fixture: 'FIXTURE_POPULATION_SERVED'     
  - name: VW_CAPACITY_TEMPLATE_CREATE
    columns:
        - name: OWNER_ID
          data_tests:
          - string_not_empty   
        - name: PARENT_CASE_TYPE
          data_tests:
          - string_not_empty
        - name: UNIT_CASE_NAME_DISPLAY
          data_tests:
          - string_not_empty
        - name: UNIT_CASE_IDS
          data_tests:
          - string_not_empty
  - name: VW_UNIT_TEMPLATE_CREATE
    columns:
        - name: OWNER_ID
          data_tests:
          - string_not_empty   
        - name: PARENT_CASE_ID
          data_tests:
          - string_not_empty
        - name: CLINIC_DISPLAY_NAME
          data_tests:
          - string_not_empty
  - name: VW_UNIT_UPDATE
    columns:
      - name: MAP_COORDINATES
        data_tests:
        - child_column_not_equal_parent_column:
                parent_table: 'CASE_CLINIC'
                parent_column_name: 'MAP_COORDINATES'
      - name: CLINIC_DISPLAY_NAME
        data_tests:
        - child_column_not_equal_parent_column_with_null_handling:
                parent_table: 'CASE_CLINIC'
                parent_column_name: 'DISPLAY_NAME'
                function_call: false 
      - name: CLINIC_PHONE_DISPLAY
        data_tests:
        - child_column_not_equal_parent_column_with_null_handling:
                parent_table: 'CASE_CLINIC'
                parent_column_name: 'PHONE_DISPLAY'
                function_call: false
      - name: CLINIC_ADDRESS_FULL_DISPLAY
        data_tests:
        - child_column_not_equal_parent_column_with_null_handling:
                parent_table: 'CASE_CLINIC'
                parent_column_name: 'ADDRESS_FULL'
                function_call: false
      - name: CLINIC_MENTAL_HEALTH_SETTINGS_DISPLAY
        data_tests:
        - child_column_not_equal_parent_column_with_null_handling:
                parent_table: 'CASE_CLINIC'
                parent_column_name: 'MENTAL_HEALTH_SETTINGS'
                function_call: true
                function_name: 'FN_MENTAL_HEALTH_SETTINGS_DISPLAY'
                function_params: ['mental_health_settings']
      - name: CLINIC_INSURANCE_DISPLAY
        data_tests:
        - child_column_not_equal_parent_column_with_null_handling:
                parent_table: 'CASE_CLINIC'
                parent_column_name: 'INSURANCE'
                function_call: true
                function_name: 'FN_INSURANCE_DISPLAY'
                function_params: ['INSURANCE']
  - name: VW_CAPACITY_UPDATE
    columns:
      - name: CASE_ID
        data_tests:
        - not_null
        - unique      
      - name: CASE_TYPE
        data_tests:
        - not_null
        - accepted_values:
            values: ['capacity']
        - string_not_empty
      - name: CLINIC_ADDRESS_FULL_DISPLAY
        data_tests:
        - child_column_not_equal_parent_column_with_null_handling:
                parent_table: 'CASE_CLINIC'
                parent_column_name: 'ADDRESS_FULL'
                function_call: false
