models:
  - name: VW_CAPACITY_UPDATE
    columns:
    - name: CASE_ID
      tests:
      - not_null
      - unique
      - relationships:
          to: source('dm_table_data', CASE_PROVIDER')
          field: case_id      
    - name: CASE_TYPE
      tests:
      - not_null
      - accepted_values:
          values: ['capacity']
      - string_not_empty
  - name: VW_CAPACITY_TEMPLATE_CREATE
    columns:
        - name: OWNER_ID
          tests:
          - string_not_empty   
        - name: PARENT_CASE_TYPE
          tests:
          - string_not_empty
        - name: UNIT_CASE_NAME_DISPLAY
          tests:
          - string_not_empty
        - name: UNIT_CASE_IDS
          tests:
          - string_not_empty
  - name: VW_UNIT_TEMPLATE_CREATE
    columns:
        - name: OWNER_ID
          tests:
          - string_not_empty   
        - name: PARENT_CASE_ID
          tests:
          - string_not_empty
        - name: CLINIC_DISPLAY_NAME
          tests:
          - string_not_empty
  - name: VW_CLINICS_CREATE_UPDATE
    columns:
        - name: CLINIC_TYPE
          tests:
          - column_not_empty
        - name: SERVICE_TYPES
            tests:
            - column_not_empty