models:
  - name: VW_CLINICS_CREATE_UPDATE
    columns:
    - name: CLINIC_TYPE
      data_tests:
      - string_not_empty
    columns:
    - name: DISPLAY_NAME
      data_tests:
      - string_not_empty   
  - name: VW_CAPACITY_UPDATE
    columns:
    - name: CASE_ID
      data_tests:
      - not_null
      - unique
      #- relationships:
      #    to: source('dm_table_data', 'custoCASE_PROVIDERmers')
      #    field: case_id      
    - name: CASE_TYPE
      data_tests:
      - not_null
      - accepted_values:
          values: ['capacity']
      - string_not_empty
  - name: VW_CAPACITY_TEMPLATE_CREATE
    columns:
        - name: OWNER_ID
          data_tests:
          - string_not_empty   
        - name: PARENT_CASE_TYPE
          data_tests:
          - string_not_empty
        - name: UNIT_CASE_NAME_DISPLAY
          data_tests:
          - string_not_empty
        - name: UNIT_CASE_IDS
          data_tests:
          - string_not_empty
  - name: VW_UNIT_TEMPLATE_CREATE
    columns:
        - name: OWNER_ID
          data_tests:
          - string_not_empty   
        - name: PARENT_CASE_ID
          data_tests:
          - string_not_empty
        - name: CLINIC_DISPLAY_NAME
          data_tests:
          - string_not_empty