models:
  - name: VW_CLINICS_CREATE_UPDATE
    columns:
    - name: CLINIC_TYPE
      tests:
      - string_not_empty
      - split_value_not_in_fixture:
              ref_fixture: 'FIXTURE_CLINIC_TYPE'
    columns:
    - name: DISPLAY_NAME
      tests:
      - string_not_empty
    - name: MENTAL_HEALTH_SETTINGS
      tests:
      - split_value_not_in_fixture:
              ref_fixture: 'FIXTURE_MENTAL_HEALTH_SETTINGS'
    - name: SERVICE_TYPES
      tests:
      - split_value_not_in_fixture:
              ref_fixture: 'FIXTURE_SERVICE_TYPES'
    - name: INSURANCE
      tests:
      - split_value_not_in_fixture:
              ref_fixture: 'FIXTURE_INSURANCE'
    - name: RESIDENTIAL_SERVICES
      tests:
      - split_value_not_in_fixture:
              ref_fixture: 'FIXTURE_RESIDENTIAL_SERVICES'
    - name: POPULATION_SERVED
      tests:
      - split_value_not_in_fixture:
              ref_fixture: 'FIXTURE_POPULATION_SERVED'     
  - name: VW_CAPACITY_UPDATE
    columns:
    - name: CASE_ID
      tests:
      - not_null
      - unique      
    - name: CASE_TYPE
      tests:
      - not_null
      - accepted_values:
          values: ['capacity']
      - string_not_empty
  - name: VW_CAPACITY_TEMPLATE_CREATE
    columns:
        - name: OWNER_ID
          tests:
          - string_not_empty   
        - name: PARENT_CASE_TYPE
          tests:
          - string_not_empty
        - name: UNIT_CASE_NAME_DISPLAY
          tests:
          - string_not_empty
        - name: UNIT_CASE_IDS
          tests:
          - string_not_empty
  - name: VW_UNIT_TEMPLATE_CREATE
    columns:
        - name: OWNER_ID
          tests:
          - string_not_empty   
        - name: PARENT_CASE_ID
          tests:
          - string_not_empty
        - name: CLINIC_DISPLAY_NAME
          tests:
          - string_not_empty